import type { LucideIcon } from "lucide-react";
import {
  ArrowLeft,
  ArrowUpDown,
  Bell,
  Building,
  Calendar,
  CalendarClock,
  Camera,
  ChartArea,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CircleFadingArrowUp,
  CloudUpload,
  Ellipsis,
  Eye,
  EyeClosed,
  File,
  Files,
  Globe,
  ListChecks,
  Loader2,
  LogOut,
  MessageCircleReply,
  MessageCircleWarning,
  MessageSquareCode,
  MinusCircle,
  Moon,
  Palette,
  PencilLine,
  Plane,
  PlusCircle,
  Puzzle,
  Scale,
  Search,
  Settings2,
  Sparkles,
  StickyNote,
  Sun,
  Tag,
  Tickets,
  Trash,
  UserCog,
  UserRound,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  account: UserCog,
  add: PlusCircle,
  ai: Sparkles,
  analytics: ChartArea,
  arrowLeft: ArrowLeft,
  arrowUpDown: ArrowUpDown,
  automaticReplies: MessageCircleReply,
  bell: Bell,
  calendar: Calendar,
  calendarRange: CalendarClock,
  camera: Camera,
  categories: ListChecks,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  edit: PencilLine,
  eye: Eye,
  eyeClosed: EyeClosed,
  file: File,
  files: Files,
  language: Globe,
  logo: Scale,
  logout: LogOut,
  minus: MinusCircle,
  moon: Moon,
  more: Ellipsis,
  organization: Building,
  palette: Palette,
  remove: Trash,
  request: MessageSquareCode,
  resend: Plane,
  search: Search,
  settings: Settings2,
  spinner: Loader2,
  sun: Sun,
  tag: Tag,
  teams: Puzzle,
  template: StickyNote,
  tickets: Tickets,
  upgrade: CircleFadingArrowUp,
  upload: CloudUpload,
  user: UserRound,
  warning: MessageCircleWarning,
};
